typography_spectrum: 0.6005375345703214
color:
  brandStrength: 0.5693937803152949
  lightness: 0.11750888219103217
  saturation: 0.8247122487518936
  rhythmicContrast: 0.5000915622804314
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.38311397819779813
author:
  name: DeiScribe
  email: deiscribepublishing@gmail.com
  url: DeiScribePub.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a9bffe4-be01-4c0f-baff-1fd85c91463e.jpg
name: DeiScribePublishing
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/16d7ef47-4b9d-4457-8f01-bd35f7771411.png
title: DeiScribe Pub.
description: 'Web, Graphic, and Photography Design'
